### ISSUE TITLE
Help me !!

### ISSUE THREAD

**Issue by lologhi** [lologhi/MassAPI#1]
Please have a look to this first version of what could be a worldwide API to retrieve nearby catholic mass, or any other religious event !

**Comment by aquilax** [comment]
Hi, I want to help. Anything in particular I should be looking for?

**Comment by lologhi** [comment]
Woaw! Great!
I think of creating a new command to parse the data from your country (hoping there is already a website for that), for example. Like [this one](https://github.com/lologhi/MassAPI/blob/master/src/MassAPIBundle/Command/MesseInfoParserCommand.php), parsing the French ugly API and trying to reorder the data in a nice model from Schema.org.

**Comment by lologhi** [comment]
Or a class that could detect the frequency of an event. Because from the french list of mass, I can retrieve particular event, but without the frequency. So I get old data quite fast.
And if you try to install the project on you localhost, you can give me your remarks so that I can update the Readme more accessible for every developer who would like to help :)

**Comment by aquilax** [comment]
Seems like in Sweden there is no centralized place at least that page says so: http://www.katolskakyrkan.se/catholic-parishes-in-sweden/mass-times

**Comment by lologhi** [comment]
Hum. Maybe you could add a Markdown table with, by country, this kind of links and a boolean about the availability of a global platform.

**Comment by aquilax** [comment]
All good ideas, will start working on one of them tonight

**Comment by lologhi** [comment]
Thanks a lot @aquilax! I'll work again on this project asap too!!
